language: rust
cache: cargo
dist: trusty
sudo: required

env:
  global:
  - PROJECT_NAME=netlyser

addons:
  apt:
    packages:
      - fakeroot

matrix:
  include:
    # Default test+release version
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

    # Extra targets for linux only
    - os: linux
      rust: stable
      env: 
      - TARGET=i686-unknown-linux-musl
      - PKG_CONFIG_ALLOW_CROSS=1
    - os: linux
      rust: stable
      env: 
      - TARGET=x86_64-unknown-linux-musl
      - PKG_CONFIG_ALLOW_CROSS=1

    # Minimum version advertised in readme
    - os: linux
      rust: 1.34.0
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: 1.34.0
      env: TARGET=x86_64-apple-darwin

    # Non-critical but interesting for upcoming Rust changes
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin

  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev; fi

before_script:
  - rustup target add $TARGET
  - cargo clean --target $TARGET --verbose

script:
  - cargo build --target $TARGET --verbose

notifications:
  email:
    on_success: never
    on_failure: always
